# Generated by Django 6.0.2 on 2026-02-17 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('content', models.TextField(blank=True, verbose_name='Contenu Markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markdown_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Markdown',
                'verbose_name_plural': 'Documents Markdown',
                'ordering': ['-created_at'],
            },
        ),
    ]
