# Generated by Django 6.0.2 on 2026-03-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_refresh_seed_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='societe',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Société'),
        ),
    ]
