# Generated by Django 6.0.2 on 2026-02-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_debut', models.CharField(max_length=100)),
                ('date_fin', models.CharField(max_length=100)),
                ('pos_x', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('hauteur', models.FloatField(default=5.0)),
                ('couleur_hex', models.CharField(default='#3b82f6', max_length=7)),
            ],
        ),
    ]
